- hosts: tictac
  name: Deploy
  gather_facts: true
  vars:
    ansible_user: root
  tasks:
    - name: Stop server
      ansible.builtin.command: rc-service tictac stop
      register: my_output # <- Registers the command output.
      changed_when: my_output.rc != 0
    - name: Rsync
      ansible.posix.synchronize:
        mode: push
        src: /home/sft/dev/tres-en-raya/
        dest: /opt/tres-en-raya-supabase/
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=build"
          - "--exclude=.svelte-kit"
          - "--exclude=.git"
      register: output
    - name: Print rsync output
      ansible.builtin.debug:
        var: output.stdout_lines
    - name: Build
      ansible.builtin.command: npm run build
      register: my_output # <- Registers the command output.
      changed_when: my_output.rc != 0
      args:
        chdir: /opt/tres-en-raya-supabase
    - name: Service file from template
      template:
        src: service.j2
        dest: /etc/init.d/tres-en-raya-supabase
        mode: '0755'
        owner: root
        group: root
    - name: Restart server
      ansible.builtin.command: rc-service tictac restart
      register: my_output # <- Registers the command output.
      changed_when: my_output.rc != 0

- hosts: proxy
  name: nginx
  vars:
    ansible_user: root
  tasks:
    - name: Generate Nginx for torocro
      template:
        src: tictac.j2
        dest: /etc/nginx/sites-available/tictac.torocro.conf

    - name: Create a symlink to enable the site
      file:
        src: /etc/nginx/sites-available/tictac.torocro.conf
        dest: /etc/nginx/sites-enabled/tictac.torocro.conf
        state: link

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
