const PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzdGtpdHNibGl0cW9maHpxY2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzg5Nzg5NjAsImV4cCI6MTk5NDU1NDk2MH0.7JS5hUrqvUJYwyTPTBWiSDvFrhipUGLo0lWZ67Kww64";
const PUBLIC_SUPABASE_URL = "https://istkitsblitqofhzqcfw.supabase.co";
export {
  PUBLIC_SUPABASE_URL as P,
  PUBLIC_SUPABASE_ANON_KEY as a
};
